service: multiple-s3-proxy

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  localPath: './../../../../../../'
  modules:
    - serverless-apigateway-service-proxy

custom:
  apiGatewayServiceProxies:
    - s3:
        path: /s3
        method: post
        action: PutObject
        bucket:
          Ref: S3Bucket
        key: my-test-object.json  # static key
        cors: true

    - s3:
        path: /s3/{key} # path param
        method: get
        action: GetObject
        bucket:
          Ref: S3Bucket
        key:
          pathParam: key
        cors: true

    - s3:
        path: /s3
        method: delete
        action: DeleteObject
        bucket:
          Ref: S3Bucket
        key:
          queryStringParam: key # query string param
        cors: true

resources:
  Resources:
    S3Bucket:
      Type: 'AWS::S3::Bucket'

  Outputs:
    S3BucketName:
      Value:
        Ref: S3Bucket
