service: kinesis-proxy

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  localPath: './../../../../../../'
  modules:
    - serverless-apigateway-service-proxy

custom:
  apiGatewayServiceProxies:
    - kinesis:
        path: /kinesis
        method: post
        streamName: { Ref: 'YourStream' }
        cors: true

resources:
  Resources:
    YourStream:
      Type: AWS::Kinesis::Stream
      Properties:
        ShardCount: 1
